
image:
  file: .gitpod.Dockerfile
ports:
    - port: 3000
      onOpen: open-browser
    - port: 3001
      onOpen: open-preview
    - port: 5432
      onOpen: ignore
tasks:
    - init: >
        (cp -n .env.example .env || true) && 
        echo "" >> .env && echo "BACKEND_URL=https://3001-${GITPOD_WORKSPACE_URL:8}" >> .env && 
        pipenv install &&
        psql -U gitpod -c 'CREATE DATABASE example;' &&
        psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d example &&
        pipenv run init && 
        pipenv run migrate && 
        pipenv run upgrade &&
        python docs/assets/greeting.py back
    - command: >
        npm install &&
        python docs/assets/greeting.py front
      openMode: split-right
