@host=https://3001-scarlet-leopon-aas2fq4a.ws-us16.gitpod.io/api

### Probar la api regresa "message": "Hello! I'm a message that came from the backend"
POST {{host}}/hello
Content-Type: application/json

### Creación de hash
POST {{host}}/hash
Content-Type: application/json

############################################################################################################

### DATOS DE UN USER
GET {{host}}/user/1
Content-Type: application/json
#Authorization: Bearer {{token}}

### REGISTER/POST DE UN USER
POST {{host}}/user
Content-Type: application/json

{
    "email":"Fab5iz@4geeks.cl",
    "password":"123456",
    "rut":"blabla",
    "name":"Placido",
    "lastname":"Perez",
    "contact":"blabla",
    "register":"blabla",
    "perfil":"tecnico",
    "fecha_nacimiento":"20-11-1995"
}

### UPDATE USER
PUT {{host}}/user/1
Content-Type: application/json

{
    "rut":"vlevle",
    "name":"Laja",
    "contact":"vlevle",
    "register":"vlevle",
    "perfil":"super mega administrador",
    "fecha_nacimiento":"31-01-1997"
}

### DELETE USER
DELETE  {{host}}/user/1
Content-Type: application/json

### USERS
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

############################################################################################################

###  @AUTH
# @name authSession
POST {{host}}/login
Content-Type: application/json

{
    "email":"Fab5iz@4geeks.cl",
    "password":"123456"
}

###
@token = {{authSession.response.body.$.token}}

### CAMBIAR CONTRASENA
PUT {{host}}/cambiarc/2
Content-Type: application/json

{
    "actual":"000000.",
    "nueva":"123123."
}

### RECUPERAR CONTRASENA
PUT {{host}}/recuperarc
Content-Type: application/json

{
    "email":"Fab5iz@4geeks.cl"
}

############################################################################################################

### VER TODOS LOS CONTRATOS
GET {{host}}/contratos
Content-Type: application/json
#Authorization: Bearer {{token}}

### VER UN CONTRATO EN ESPECIFICO
GET {{host}}/contrato/1
Content-Type: application/json
#Authorization: Bearer {{token}}

### CREAR CONTRATO
POST {{host}}/contrato
Content-Type: application/json

{
    "id_project": "Nombrecito bueno",
    "region":"Metropolitana Nacional",
    "comuna":"Que feo",
    "sector":"Casa de mi pana",
    "plano":"Cartesianito",
    "obra_descripcion":"Descrita",
    "planta_matriz":"Planta del pie",
    "comentario":"Este es un buen proyecto"
}

### UPDATE CONTRATO
PUT {{host}}/contrato/1
Content-Type: application/json

{
    "id_project":"vlevle",
    "region":"vlevle",
    "comuna":"vlevle",
    "sector":"vlevle",
    "plano":"vlevle",
    "obra_descripcion":"vlevle",
    "planta_matriz":"vlevle",
    "comentario":"vlevle"
}

### DELETE CONTRATO
DELETE  {{host}}/contrato/2
Content-Type: application/json

############################################################################################################

### VER TODAS LAS ORDENES DE TRABAJO DE UN CONTRATO
GET {{host}}/orders/1
Content-Type: application/json
#Authorization: Bearer {{token}}

### VER DATOS DE UNA ORDEN DE TRABAJO
GET {{host}}/order/1
Content-Type: application/json
#Authorization: Bearer {{token}}

### CREAR UNA ORDEN DE TRABAJO
POST {{host}}/order
Content-Type: application/json

{
    "id_contrato":1,
    "id_nombre":"Mufa56",
    "tipo":"blabla",
    "direccion":"Casa",
    "descripcion":"Casita"
}

### UPDATE UNA ORDEN DE TRABAJO
PUT {{host}}/order/2
Content-Type: application/json

{
    "id_nombre":"vlevle",
    "tipo":"Laja",
    "direccion":"vlevle",
    "descripcion":"vlevle"
}

### DELETE ORDEN DE TRABAJO
DELETE  {{host}}/order/3
Content-Type: application/json

############################################################################################################



############################################################################################################

### VER CONTRATOS DE UN USER ----> NO FUNCIONA
GET {{host}}/contratos_user/1
Content-Type: application/json
#Authorization: Bearer {{token}}

############################################################################################################


{
    "email":"hola@luis.cl",
    "password":"123456",
    "rut":"blabla",
    "name":"Luis",
    "lastname":"Salgado",
    "contact":"blabla",
    "register":"blabla",
    "perfil":"tecnico",
    "fecha_nacimiento":"14-08-1992"
}