"""empty message

Revision ID: 0e8502ed9dfc
Revises: e632d1fe4fc2
Create Date: 2021-08-28 04:46:25.092280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8502ed9dfc'
down_revision = 'e632d1fe4fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordentrabajo', sa.Column('direccion', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordentrabajo', 'direccion')
    # ### end Alembic commands ###
