"""empty message

Revision ID: 22df051dddfe
Revises: ff63e705e3a4
Create Date: 2021-08-24 07:31:05.832004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22df051dddfe'
down_revision = 'ff63e705e3a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrato', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    op.alter_column('contrato', 'plano',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('contrato', 'planta_matriz',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('contrato', 'cerco_geo_latitud')
    op.drop_column('contrato', 'cerco_geo_longitud')
    op.drop_column('contrato', 'prioridad')
    op.drop_column('contrato', 'hp')
    op.add_column('user', sa.Column('fecha_registro', sa.DateTime(), nullable=True))
    op.alter_column('user', 'contact',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'fecha_nacimiento',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'rut',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)
    op.drop_column('user', 'register')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('register', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('user', 'rut',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'lastname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('user', 'fecha_nacimiento',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('user', 'contact',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('user', 'fecha_registro')
    op.add_column('contrato', sa.Column('hp', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('contrato', sa.Column('prioridad', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('contrato', sa.Column('cerco_geo_longitud', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('contrato', sa.Column('cerco_geo_latitud', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.alter_column('contrato', 'planta_matriz',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('contrato', 'plano',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('contrato', 'fecha_registro')
    # ### end Alembic commands ###
