"""empty message

Revision ID: ba94cd78e207
Revises: 22df051dddfe
Create Date: 2021-08-26 19:23:15.331622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba94cd78e207'
down_revision = '22df051dddfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contrato', 'comentario',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('contrato', 'comuna',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('contrato', 'obra_descripcion',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('contrato', 'region',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('contrato', 'sector',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('user', 'perfil',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'perfil',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('contrato', 'sector',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contrato', 'region',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contrato', 'obra_descripcion',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('contrato', 'comuna',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('contrato', 'comentario',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
